<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to ObjectStyle LLC under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ObjectStyle LLC licenses
  this file to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.bootique.bom</groupId>
        <artifactId>bootique-bom-parent</artifactId>
        <version>4.0-M6</version>
    </parent>

    <artifactId>bootique-bom-tests-newest</artifactId>
    <packaging>jar</packaging>

    <name>bootique-bom-tests-newest: Bootique BOM integration tests, newest ORM stack</name>
    <description>Integration tests for the BOM modules, combined with the newest Cayenne 5.0 / Agrest 6 / LinkMove 4 stack.</description>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.bootique.bom</groupId>
                <artifactId>bootique-bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.ehcache</groupId>
                <artifactId>ehcache</artifactId>
                <version>${ehcache.version}</version>
                <classifier>jakarta</classifier>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>javax.cache</groupId>
                        <artifactId>cache-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jaxb</groupId>
                <artifactId>jaxb-runtime</artifactId>
                <version>${glassfish.jaxb3.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

        <!-- Newest mutually-exclusive stack: Cayenne 5.0, Agrest 6, LinkMove 4 -->
        <dependency>
            <groupId>io.bootique.agrest</groupId>
            <artifactId>bootique-agrest6</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.agrest</groupId>
            <artifactId>bootique-agrest6-swagger</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.cayenne</groupId>
            <artifactId>bootique-cayenne50</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.cayenne</groupId>
            <artifactId>bootique-cayenne50-jcache</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.linkmove</groupId>
            <artifactId>bootique-linkmove4</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.linkmove</groupId>
            <artifactId>bootique-linkmove4-csv</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.linkmove</groupId>
            <artifactId>bootique-linkmove4-rest</artifactId>
        </dependency>

        <!-- Version-neutral modules. Present in both "legacy" and "newest" test stacks -->
        <dependency>
            <groupId>io.bootique</groupId>
            <artifactId>bootique</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.aws</groupId>
            <artifactId>bootique-aws2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.aws</groupId>
            <artifactId>bootique-aws2-s3</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.aws</groupId>
            <artifactId>bootique-aws2-secrets</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.curator</groupId>
            <artifactId>bootique-curator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.cxf</groupId>
            <artifactId>bootique-cxf-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.cxf</groupId>
            <artifactId>bootique-cxf-jaxrs</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.cxf</groupId>
            <artifactId>bootique-cxf-jaxws-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.cxf</groupId>
            <artifactId>bootique-cxf-jaxws-server</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.docker</groupId>
            <artifactId>bootique-docker</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.flyway</groupId>
            <artifactId>bootique-flyway</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jcache</groupId>
            <artifactId>bootique-jcache</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jdbc</groupId>
            <artifactId>bootique-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jdbc</groupId>
            <artifactId>bootique-jdbc-hikaricp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jdbc</groupId>
            <artifactId>bootique-jdbc-hikaricp-instrumented</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jersey</groupId>
            <artifactId>bootique-jersey</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jersey</groupId>
            <artifactId>bootique-jersey-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jersey</groupId>
            <artifactId>bootique-jersey-beanvalidation</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jersey</groupId>
            <artifactId>bootique-jersey-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jersey</groupId>
            <artifactId>bootique-jersey-client-instrumented</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jetty</groupId>
            <artifactId>bootique-jetty</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jetty</groupId>
            <artifactId>bootique-jetty-cors</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jetty</groupId>
            <artifactId>bootique-jetty-instrumented</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jetty</groupId>
            <artifactId>bootique-jetty-websocket</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.job</groupId>
            <artifactId>bootique-job</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.job</groupId>
            <artifactId>bootique-job-instrumented</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.jooq</groupId>
            <artifactId>bootique-jooq</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.kafka</groupId>
            <artifactId>bootique-kafka-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.kafka</groupId>
            <artifactId>bootique-kafka-streams</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.liquibase</groupId>
            <artifactId>bootique-liquibase</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.logback</groupId>
            <artifactId>bootique-logback</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.logback</groupId>
            <artifactId>bootique-logback-smtp</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.metrics</groupId>
            <artifactId>bootique-metrics</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.metrics</groupId>
            <artifactId>bootique-metrics-healthchecks</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.mongo</groupId>
            <artifactId>bootique-mongo-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.mongo</groupId>
            <artifactId>bootique-mongo-morphia</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.mvc</groupId>
            <artifactId>bootique-mvc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.mvc</groupId>
            <artifactId>bootique-mvc-freemarker</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.mvc</groupId>
            <artifactId>bootique-mvc-mustache</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.mybatis</groupId>
            <artifactId>bootique-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.opentelemetry</groupId>
            <artifactId>bootique-opentelemetry</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.rabbitmq</groupId>
            <artifactId>bootique-rabbitmq-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.shiro</groupId>
            <artifactId>bootique-shiro</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.shiro</groupId>
            <artifactId>bootique-shiro-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.shiro</groupId>
            <artifactId>bootique-shiro-jwt</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.shiro</groupId>
            <artifactId>bootique-shiro-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.shiro</groupId>
            <artifactId>bootique-shiro-web-jwt</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.shiro</groupId>
            <artifactId>bootique-shiro-web-mdc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.shiro</groupId>
            <artifactId>bootique-shiro-web-oidc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.simplejavamail</groupId>
            <artifactId>bootique-simplejavamail</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.swagger</groupId>
            <artifactId>bootique-swagger</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.swagger</groupId>
            <artifactId>bootique-swagger-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>io.bootique.tapestry</groupId>
            <artifactId>bootique-tapestry59</artifactId>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>io.bootique.cayenne</groupId>
            <artifactId>bootique-cayenne50-junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.bootique</groupId>
            <artifactId>bootique-junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.bootique.agrest</groupId>
            <artifactId>bootique-agrest-junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.bootique.aws</groupId>
            <artifactId>bootique-aws2-junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.bootique.aws</groupId>
            <artifactId>bootique-aws2-s3-junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.bootique.jdbc</groupId>
            <artifactId>bootique-jdbc-junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.bootique.jdbc</groupId>
            <artifactId>bootique-jdbc-junit-derby</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.bootique.jdbc</groupId>
            <artifactId>bootique-jdbc-junit-testcontainers</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.bootique.jersey</groupId>
            <artifactId>bootique-jersey-client-junit-wiremock</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.bootique.jetty</groupId>
            <artifactId>bootique-jetty-junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.bootique.mongo</groupId>
            <artifactId>bootique-mongo-junit</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.bootique.rabbitmq</groupId>
            <artifactId>bootique-rabbitmq-junit</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Non-Bootique dependencies needed for the stack to run -->
        <dependency>
            <groupId>org.ehcache</groupId>
            <artifactId>ehcache</artifactId>
            <classifier>jakarta</classifier>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <!-- Checking that the BOM produces a consistent dependency graph. Intentionally declared here and -->
            <!-- not in the parent POM, so that it applies to the test modules only, and never to the BOM itself. -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>3.6.2</version>
                <executions>
                    <execution>
                        <id>enforce-dependency-versions</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <!-- Fails when Maven's "nearest wins" resolution picks a version lower than -->
                                <!-- some other path requires, i.e. a silent downgrade -->
                                <requireUpperBoundDeps />

                                <!-- Fails when any two paths disagree on a version at all -->
                                <dependencyConvergence />

                                <banDuplicatePomDependencyVersions />
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


    <profiles>
        <profile>
            <id>rat</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.rat</groupId>
                        <artifactId>apache-rat-plugin</artifactId>
                        <configuration>
                            <excludes>
                                <exclude>src/main/resources/io/bootique/bom/cayenne/cayenne-project.xml</exclude>
                                <exclude>src/main/resources/io/bootique/bom/cayenne/datamap.map.xml</exclude>
                                <exclude>src/main/resources/templates/io/bootique/bom/mvc/r1/t1.mustache</exclude>
                                <exclude>**/*.yml</exclude>
                                <exclude>**/*.json</exclude>
                                <exclude>derby.log</exclude>
                            </excludes>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
